services:
  - type: web
    name: spic-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        value: mr.vishalsingh987@gmail.com
      - key: GMAIL_PASS
        value: ewficvtigzzypbrt
      - key: GOOGLE_SHEET_ID
        value: 1m7NagzbSuyU4qsOX7ul43ETPiUOyAkkzb_aKGYc3xd4
      - key: GOOGLE_SHEET_WEBHOOK_URL
        value: https://script.google.com/macros/s/AKfycbxvOswFrS4wNLjRdlYaCAQ-2btQcXH8dQLBa6gPGD0nqHJmlNawsDNFrk2cDrzfy2nk0A/exec
